package org.jakegodsall.models.enums;

public enum Tense {
    PAST, PAST_SIMPLE, PAST_PROGRESSIVE, PAST_PERFECT,

    PRESENT, PRESENT_SIMPLE, PRESENT_PERFECT,

    FUTURE, FUTURE_PERFECT,

    CONDITIONAL, CONDITIONAL_PERFECT
}
